# -*- coding: utf-8 -*-
"""T. M 01 Jeeva Assignment 1 z

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ai4blm3FS9ockaE06VgE_qO_jWlbSNyE

#create and load dataset
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv('/content/Data1 (1).csv')
df.head()

"""#univariate analysis"""

sns.distplot(df['Salary'])

sns.boxplot(df['Salary'])

sns.barplot(df['Age'])

sns.scatterplot(df['Country'])

"""#Bi-varient Analysis"""

sns.barplot(x='Age',y='Salary',data=df)

sns.violinplot(x='Country',y='Age',data=df)

sns.barplot(x='Salary',y='Purchased',data=df)

sns.scatterplot(x='Age',y='Salary',data=df)

"""#Multi-varient Analysis"""

sns.heatmap(df.corr())

"""#Discriptive Stat"""

df.describe(include='all')

df.describe()

"""#Data wrangling or Handle Missing Values"""

df.head()

df.isnull().sum()

df.info()

df['Salary'].mean()

df.head()

"""# Replace Null to Value"""

df['Salary'].fillna(20000.9,inplace=True)
df.head()